### ISSUE TITLE
Feat.req. Win binary 

### ISSUE THREAD

**Issue by necros2k7** [soulweaver91/project-carrot#69]
subj

**Comment by soulweaver91** [comment]
No prebuilt binaries of the main game executable were purposefully provided in the past, since my vision at the time was that the first suitable occasion for that would be only when the Shareware Demo episodes would be in sufficiently playable state and when I had managed to make the setup more user friendly. Due to motivation issues and the limited time I'd rather allocate into my other projects instead, the development of Project Carrot has been (again) stalled for close to two years and counting, though, so I guess that time isn't still coming soon.

You can get the 64-bit Windows binaries of PC + the associated tools and dependencies from [this ZIP here](https://soulweaver.fi/carrot-master-2019-07-17.zip). You will still need to do the necessary steps using the original data files to actually make use of the game executable, though, as documented in the readme of this repository. I also included the PowerShell scripts that can be used to convert every tileset and level in your Jazz directory at once, but they need some extra work (see the comment inside the level one in particular for what to do to use them and what kind of parameters they want).

I'll stress that, due to my limited resources and due to the nature of these binaries, I won't have time to help you further if you can't get the game running with what I've provided. Please also don't file any issues about bugs or inconsistencies vs. JJ2; I already know the engine is buggy in some places and it was never supposed to be used in this state. I'll thank you for your interest towards Project Carrot, though!
